# === Spring ===
spring:
  # === mariadb ===
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dev?autoReconnect=true&useSSL=false
    username: kim
    password: kim123
    hikari:
      auto-commit: false
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: basedbcp
  # === jpa ===
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
#        jdbc:
#          batch_size: 50
#          batch_versioned_data: true
#          generate_statistics: true
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  # === redis ===
  data:
    redis:
      host: localhost
      port: 6379
      password: kim456
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  # === rabbitmq ===
  rabbitmq:
    host: localhost
    port: 5672
    username: kim
    password: kim789
  # === openfeign ===
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000
            loggerLevel: full
          CALL-API:
            connectTimeout: 5000
            readTimeout: 60000
  pid:
    file: ./pid/base-api.pid

# === Swagger ===
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    doc-expansion: none
    groups-order: desc
    operations-sorter: method
  show-actuator: true
  paths-to-match:
    - /**

# === Logging ===
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%-15thread][%-36logger{36}.%-20method:%-4line] - %msg%n"
  level:
    root: info
    sql: info
    web: info

# === p6spy ===
decorator:
  datasource:
    p6spy:
      enable-logging: true

# === key properties(사용자 지정) ===
keys:
  apiKey: AAAAAAAAAA
  apiKey2: BBBBBBBBBB